#created by kamuszhou@tencent.com on April 18 2018

projname := cuttle

CPPFLAGS += -std=c++11 -g -DVERSION_MAJOR=1 -DVERSION_MINOR=0 
#CXXFLAGS += -fvisibility=hidden -Wfatal-errors
LINKFLAGS += -lsodium -lboost_random -lzookeeper_mt

include ../common.mk
