#created by kamuszhou@tencent.com on April 18 2018

projname := cuttle

CPPFLAGS += -std=c++0x -g -DVERSION_MAJOR=1 -DVERSION_MINOR=0 -DBOOST_LOG_DYN_LINK
#CXXFLAGS += -fvisibility=hidden -Wfatal-errors
LINKFLAGS += -lczmq -lzmq -lsodium

include ../common.mk
