#created by kamuszhou@tencent.com on March 17 2017

soname := libotter.so

CPPFLAGS += -std=c++0x -g -DVERSION_MAJOR=1 -DVERSION_MINOR=0 -fPIC
#CXXFLAGS += -fvisibility=hidden -Wfatal-errors
LINKFLAGS += 

include ../common.mk
